### ISSUE TITLE
Request: remove exclamation points from exceptions

### ISSUE THREAD

**Issue by rlabbe** [prettytable/prettytable#100]
This is an example of an exception I just got:

    Exception: Invalid field name: f!

That's very confusing; I was trying to figure out how I passed the string 'f!'

Compare this to any Python exception:

    3/0 
    ZeroDivisionError: division by zero

No exclamation point. I'm not aware of any built in exception in Python that uses exclamation points. 

If you must stick with using exclamation points or punctuation, please use quotes to make the field readable:

    Exception: Invalid field name: 'f'!

**Comment by hugovk** [comment]
Yep, sounds reasonable, please see PR https://github.com/jazzband/prettytable/pull/101.
