### ISSUE TITLE
Add custom format functions for field output to prettytable (For example to format date/datetime)

### ISSUE THREAD

**Issue by BeldrothTheGold** [prettytable/prettytable#105]
Hi,

Is it possible to have prettytable output datetime objects with a specific format in a field?

The default format is OK, but I would love it if I could customize the display format. Currently I am converting the datetime objects to strings before inserting them into the table. However, I think it would be better to insert them directly to make it easier to sort by date. 

Then prettytable could format them however desired when requesting the table string. 

V/R
Scot

**Comment by BeldrothTheGold** [comment]
I was thinking it might be useful to add something more high level than specifically adding support for datetime format strings.

Something like adding a custom format function or ToString function to a field. Something that prettytable would call for each value in a column when generating the format string. 

Something like this:

```python
table.format_func["FieldName"] = lambda x: x.strftime("%Y-%m-%d %H:%M GMT")
```

**Comment by hugovk** [comment]
Please can you have a look at PR https://github.com/jazzband/prettytable/pull/136 and see if it would address your needs?

**Comment by BeldrothTheGold** [comment]
> Please can you have a look at PR #136 and see if it would address your needs?

Yes, looks great. Thanks!
