### ISSUE TITLE
Add function that adds column of average values in table

### ISSUE THREAD

**Issue by erictzimas** [prettytable/prettytable#107]
Hello, i would suggest creating a custom function that adds a column of the averages of each row to the table if the values are numerical. I will create a PR to showcase such functionality.

**Comment by hugovk** [comment]
Hi, thanks for the suggestion!

I think I might decline this as it seems pretty specialised and PrettyTable isn't intended to be a spreadsheet. And it should be straightforward to pre-calculate whatever values are needed and add them as a column.
