### ISSUE TITLE
Unable to import prettytable

### ISSUE THREAD

**Issue by fluidjeel** [prettytable/prettytable#120]
Environment:

- OS: Windows10
- PythonVersion: 3.7
- IDE: PyCharm(3.7 Interpreter)

Error:
```
Traceback (most recent call last):
  File "D:/Python-2021-ZTE/Turtle/prettytable.py", line 1, in <module>
    from prettytable import PrettyTable
  File "D:\Python-2021-ZTE\Turtle\prettytable.py", line 1, in <module>
    from prettytable import PrettyTable
ImportError: cannot import name 'PrettyTable' from 'prettytable' (D:\Python-2021-ZTE\Turtle\prettytable.py)
```

code:

```python
from prettytable import PrettyTable

my_table = PrettyTable()
my_table.field_names = ["City", "Area", "Population", "Malls"]
my_table.add_row(["Bangalore", "JP Nagar", "1million", "1"])
my_table.add_row(["Belgaum", "SomeNeighborhood", "1million", "0"])
my_table.add_row(["Bhubaneshwar", "Patia", "1million", "2"])
```

Installed Via:
```
python -m pip install -U prettytable
```

**Comment by hugovk** [comment]
How did you install?

How do you run your script?

It's important to make sure you use the same Python interpreter to install and run, that's why the README recommends `python -m pip install -U prettytable`.

See https://snarky.ca/why-you-should-use-python-m-pip/ for more details.

**Comment by bivash143** [comment]
1. Make sure Pip is installed or not by typing command
`pip --version`
**if (not installed)**:
go to the below link it will guide you, how to install pip
[https://phoenixnap.com/kb/install-pip-windows](url)
**if (installed)**:
move to 2. step

2. use the below command to install prettytable
`python3 -m pip install -U prettytable`

3. check whether it installed successfully or not by typing command in cmd
`python3`
`import prettytable`

if no error show then you are all good
enter `quit()`

**Comment by fluidjeel** [comment]
@bivashchakraborty554  i dont think there is any executable for python3 for windows. Its named as python only. 

```
py -3 -m pip install -U prettytable
Defaulting to user installation because normal site-packages is not writeable
Collecting prettytable
  Using cached prettytable-2.1.0-py3-none-any.whl (22 kB)
Requirement already satisfied: wcwidth in c:\users\manny\appdata\roaming\python\python39\site-packages (from prettytable) (0.2.5)
Installing collected packages: prettytable
Successfully installed prettytable-2.1.0
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the 'C:\Program Files\Python39\python.exe -m pip install --upgrade pip' command.
````

**Comment by fluidjeel** [comment]
Issue in my local setup. Facing issue with my other imports as well. God i hate windows ...arrrgghh

**Comment by hammale2003** [comment]
> Issue in my local setup. Facing issue with my other imports as well. God i hate windows ...arrrgghh

i have the same problem could you please show me how did you fixe it ?
