### ISSUE TITLE
Merge with lmaurits/prettytable?

### ISSUE THREAD

**Issue by ksze** [prettytable/prettytable#13]
It looks like @lmaurits is the original author (i.e. same person as the Google Code archived repo owner).

It's unfortunate that, when this was exported from Google Code, GitHub isn't able to automatically trace this repo as a fork of https://github.com/lmaurits/prettytable. There are also many other "forks" that GitHub hasn't automatically traced.

Since you seem to have put the most effort among the forkers, maybe make @lmaurits aware of your fork and somehow arrange to merge back to the original, or take custody of the package on PyPI so you can publish updated versions?

**Comment by hugovk** [comment]
In the past, I've emailed GitHub support to get different repos that had been imported from Google Code linked as forks. That was a few years ago.

I see https://github.com/lmaurits/prettytable hasn't been updated in 5 years, so I'm not sure of the value of linking. It's probably a good idea to keep the repo under Jazzband to help keep it maintained. However, @lmaurits is properly credited as author in the `setup.py` metadata, and I'd suggest giving them rights to this repo as well, if they're interested.

**Comment by hugovk** [comment]
@lmaurits Hi Luke! Would you like to join [Jazzband](https://jazzband.co/) for merge rights in this repo to help keep it maintained? No problem if you've moved on to other things, and thanks for PrettyTable!

**Comment by hugovk** [comment]
Closing this issue, but the offer is still open 👍
