### ISSUE TITLE
no name prettytable

### ISSUE THREAD

**Issue by xigrug** [prettytable/prettytable#14]
conda list prettytable
> packages in environment at /data/c03n02/cliu/software/anaconda2019/envs/skl:
> Name                    Version                   Build  Channel
>prettytable               0.7.2                      py_3    conda-forge

I have import it successuflly. But when restart this envrionment.
python -c "import prettytable" shows:
ModuleNotFoundError: No module named 'prettytable'

conda list prettytable is still in the print

python is 3.6.7 conda is 4.7.5

**Comment by jhermann** [comment]
Try `which python` and compare, try `python3`, try an absolute path to `python`. 

Basically, the most likely error is calling the wrong python binary.
