### ISSUE TITLE
Test on Python 3.10 final

### ISSUE THREAD

**Issue by hugovk** [prettytable/prettytable#142]
![image](https://user-images.githubusercontent.com/1324225/138235138-a1e843d9-72bc-41c3-99f0-f28e66fab63f.png)

Python 3.10 final was released this month:

* https://discuss.python.org/t/python-3-10-0-is-now-available/10955

That means we can switch testing from `3.10-dev` to `3.10` on the CI.

Edit the CI config file to switch, but note this:

* https://dev.to/hugovk/the-python-3-1-problem-85g

And put quotes around all the Python versions.

**Comment by NarayanAdithya** [comment]
I want to try but where is the CI configuration file I will have to change?

**Comment by hugovk** [comment]
It's in `.github/workflows/test.yml`

**Comment by NarayanAdithya** [comment]
So basically I just have to add the new version to it right referring the link you have tagged @hugovk . If thats it then do assign me this task.

**Comment by hugovk** [comment]
Just go ahead and create a PR, thanks!
