### ISSUE TITLE
What does `def _str_block_width(val)` return?

### ISSUE THREAD

**Issue by ElusiveTau** [prettytable/prettytable#15]
```python
def _str_block_width(val):
    return sum(itermap(_char_block_width, itermap(ord, _re.sub("", val))))
```

I'm trying to understand the code and I can't find documentation for `itermap()`. What the heck is `ord`?

**Comment by ElusiveTau** [comment]
`_str_block_width()` is called in the definition of `_get_size(text)`:

```python
def _get_size(text):
    lines = text.split("\n")
    height = len(lines)
    width = max(_str_block_width(line) for line in lines)
    return (width, height)
```

```python
def _str_block_width(val):
    return sum(itermap(_char_block_width, itermap(ord, _re.sub("", val))))
```

Which seems to return the number of characters in `line`. If the purpose of: 

```python
width = max(_str_block_width(line) for line in lines)
```

is to find the maximum number of characters among the list of strings, `lines`, couldn't we accomplish that using the following: 

```python
width = max(list(map(len, lines)))
```
?

**Comment by hugovk** [comment]
> I'm trying to understand the code and I can't find documentation for `itermap()`. What the heck is `ord`?

`itermap` is `map` on Python 3 and `itertools.imap` on 2.7:

https://github.com/jazzband/prettytable/search?q=itermap

```pycon
>>> help(map)
Help on class map in module builtins:

class map(object)
 |  map(func, *iterables) --> map object
 |
 |  Make an iterator that computes the function using arguments from
 |  each of the iterables.  Stops when the shortest iterable is exhausted.
 |
 |  Methods defined here:
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __next__(self, /)
 |      Implement next(self).
 |
 |  __reduce__(...)
 |      Return state information for pickling.
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
```

```pycon
>>> help(ord)
Help on built-in function ord in module builtins:

ord(c, /)
    Return the Unicode code point for a one-character string.
```

**Comment by hugovk** [comment]
> Which seems to return the number of characters in `line`. If the purpose of:
> 
> ```python
> width = max(_str_block_width(line) for line in lines)
> ```
> 
> is to find the maximum number of characters among the list of strings, `lines`, couldn't we accomplish that using the following:
> 
> ```python
> width = max(list(map(len, lines)))
> ```
> 
> ?

Possibly, and tests pass with the change, but `_str_block_width` now looks like this and uses `wcwidth` to be more careful with non-ASCII character widths:

```python
def _str_block_width(val):
    return wcwidth.wcswidth(_re.sub("", val))
```
