### ISSUE TITLE
New PyPI release?

### ISSUE THREAD

**Issue by hugovk** [prettytable/prettytable#18]
The last release on PyPI is 0.7.2 from Apr 7, 2013.

* https://pypi.org/project/PrettyTable/#history

There's been a few fixes in the past 6 years, would it be possible to make a new release to PyPI?

Ping @flaper87

Thank you!

**Comment by vinayak-mehta** [comment]
@flaper87 Just bumping this in your inbox.

**Comment by geckon** [comment]
This would actually be really nice. @flaper87, pretty please? :)

**Comment by hugovk** [comment]
I see this project is part of [JazzBand](https://jazzband.co/), which should be able to help get a release out.

@jezdez Looks like this project hasn't done the JazzBand checklist yet. Should we create an issue and then help get a release out?

**Comment by jezdez** [comment]
Huh, you're right, odd. A while ago we had troubles with GitHub API-throttling us. FWIW, if we can get a release ready I'm happy to step in for release confirmation if there is no project lead.

**Comment by hugovk** [comment]
I added a checklist: https://github.com/jazzband/prettytable/issues/22.

**Comment by luzik** [comment]
Maybe it is possible to release package under another name ?

**Comment by flaper87** [comment]
Jeeeez, this ended up being filtered out by gmail.  I am soooooo sorry about this. I'm happy to give access to the Pypi project to Jazzband. What should I do to make prettytable releasable by jazzband?

**Comment by jezdez** [comment]
@flaper87 See #22 for the TODOs.

**Comment by flaper87** [comment]
> @flaper87 See #22 for the TODOs.

Done! Sorry again for having missed these notifications :(

**Comment by hugovk** [comment]
Once we get things ready in https://github.com/jazzband/prettytable/issues/22, I plan to make a new release.

As it's been a long time since the [last release](https://pypi.org/project/PrettyTable/#history) (0.7.2, Apr 7, 2013), I suggest to make a release of what's in current master.

What version number?

Changes since 0.7.2: https://github.com/jazzband/prettytable/compare/0.7.2...master

This release will include dropping EOL Python 2.4-2.6, 3.0-3.3 (https://github.com/jazzband/prettytable/pull/5) and 3.4 (https://github.com/jazzband/prettytable/pull/16). [SemVer](https://semver.org/) says to bump the major version, except 0.x is for initial development with no stable API, and anything may change. However, PrettyTable has been out for a long time, so we can take it that SemVer has not been in use.

I propose we use SemVer and make this release PrettyTable 1.0 as so much time has passed and because Python versions have been dropped.

Then, after release, I suggest dropping Python 2.7 and modernising the codebase, and releasing later with PrettyTable 2.0.

**Comment by hugovk** [comment]
I think we're ready to release!

* [x] Changelog updated and merged: https://github.com/jazzband/prettytable/pull/28

* [x] Merge https://github.com/jazzband/prettytable/pull/34 for setuptools_scm

* [ ] Just need to update the actual release date on release day: https://github.com/jazzband/prettytable/blob/master/CHANGELOG.md#prettytable-10---unreleased

@jezdez Please could you hook up the CI for Jazzband releases (#22)?

Alternatively, @flaper87 could make the release, or I'd be happy to do so if you could add me to PyPI? I'm also hugovk there.

I could also automate it to deploy to TestPyPI on merges to master, and to production PyPI for tags, like [this](https://github.com/hugovk/pypistats/blob/66123ff04b2a17bc9ead7d04c92f2f51715ae2de/.travis.yml#L30-L53).

**Comment by andrewgy8** [comment]
Any updates on the release? I can help out where necessary.

**Comment by hugovk** [comment]
Ping @flaper87

**Comment by flaper87** [comment]
> Ping @flaper87 

I'll let @jezdez decide what the best next step is here. I've not been following this project for a bit or the jazzband processes for that matter.

I've done the steps in #22 that are required to pass this on.

I'll now remove myself as a maintainer of this project on pypi to reduce confusion and set expectations right. 😊🤗

**Comment by ericpre** [comment]
It sounds like @hugovk is keen to do the release but it doesn't seem to be listed as maintainer on pypi?

**Comment by hugovk** [comment]
I've posted a request for help at https://github.com/jazzband-roadies/help/issues/202. If nothing happens, another option to consider is a [PEP 541 transfer](https://www.python.org/dev/peps/pep-0541/).

**Comment by andrewgy8** [comment]
🤔 Correct me if Im wrong but I thought the whole point of Jazzband was so these sorts of things dont happen?

**Comment by hugovk** [comment]
That is the idea, and it resolves many of the issues, but unfortunately we've hit a bottleneck in this particular area. See also https://github.com/jazzband-roadies/help/issues/196.

**Comment by andrewgy8** [comment]
👍 Yeah, doesn't seem easy. Well, if anyone needs help, Im willing to give some of my time!

**Comment by flaper87** [comment]
@hugovk I have added you as a maintainer of PrettyTable on Pypi!

This may be the fastest way. If you have time, it would be great to setup CI as you described in https://github.com/jazzband-roadies/help/issues/202

**Comment by hugovk** [comment]
@flaper87 Thank you!

I don't have access to the Jazzband backend to set up CI releasing there (only Jazzband roadies can), but I can automate  deploys to TestPyPI on merges to master, and to production PyPI for tags, using https://github.com/pypa/gh-action-pypi-publish. I'll get that set up and plan to get a new release out in a week or so!

**Comment by hugovk** [comment]
OK, I've made PR https://github.com/jazzband/prettytable/pull/57 to automate deploys, but looks like we've hit another roadie-only blocker: we'll need to put PyPI API tokens into this repo's secret settings. I can create them but I don't have access to this repo's settings.

If it can't be resolved, one option would be to move this repo to another organisation.

But before considering that, the immediate solution is to manually `twine upload`, and I'll also make a release checklist for this.

**Comment by hugovk** [comment]
Good news!

Seven years after the last release, PrettyTable 1.0.0 is out!

![image](https://user-images.githubusercontent.com/1324225/95025152-7e5ccb80-0690-11eb-99d8-d779cfbd40d0.png)

https://pypi.org/project/prettytable/1.0.0/

Thanks everyone for your help and patience!

**Comment by andrewgy8** [comment]
Great work and persistence @hugovk ! 🍪
