### ISSUE TITLE
ColorTable: highlight a column

### ISSUE THREAD

**Issue by tdegeus** [prettytable/prettytable#196]
Thanks for the great library!

I would like to print a table in which I highlight one column, for example using green letters. I could not find how to do this

**Comment by hugovk** [comment]
One way is to colour your data before putting it in the table:

```python
from prettytable import PrettyTable
from termcolor import colored  # pip install termcolor

x = PrettyTable()

column1 = ["a", "b", "c"]
column2 = ["d", "e", "f"]
column3 = ["g", "h", "i"]

column2 = [colored(cell, "green") for cell in column2]

x.add_column("First", column1)
x.add_column(colored("Second", "yellow"), column2)
x.add_column("Third", column3)

print(x)
```

![image](https://user-images.githubusercontent.com/1324225/189067785-b47e7714-d979-41a8-a183-e9279cc4c2d3.png)

**Comment by tdegeus** [comment]
That is a solution indeed, thanks!
