### ISSUE TITLE
Compatibility with PTable

### ISSUE THREAD

**Issue by jayvdb** [prettytable/prettytable#23]
Ideally a upcoming major version of PrettyTable should also be compatible with https://github.com/kxxoling/PTable/, a very prominent and adopted fork which also quickly slid into non-maintained status.  The main problem is that it also uses installed name `prettytable`, but as a namespace `prettytable/`, and Python 3.7 (and probably earlier) will ignore `prettytable.py` when `prettytable/` exists.  And of course pip and setuptools will happy install both PrettyTable and PTable despite the clash.

There are not a lot of differences - most of the differences are patches which were submitted to PrettyTable but were not being merged at the time.  It would be good to rectify this conflict.

**Comment by hugovk** [comment]
Pull requests welcome!

**Comment by hugovk** [comment]
See also https://github.com/jazzband/prettytable/issues/74 and https://github.com/madebr/ptable2/issues/8.

Will close this as there's more info in those. Thanks for opening the issue!
