### ISSUE TITLE
Import docs from Google Code Archive

### ISSUE THREAD

**Issue by hugovk** [prettytable/prettytable#25]
The README says:

> *This tutorial is distributed with PrettyTable and is meant to serve
as a "quick start" guide for the lazy or impatient.  It is not an
exhaustive description of the whole API, and it is not guaranteed to be
100% up to date.  For more complete and update documentation, check the
[PrettyTable wiki](https://code.google.com/archive/p/prettytable/wikis).*

The wiki is on the old Google Code Archive:

* https://code.google.com/archive/p/prettytable/wikis

And links to two pages:

* https://code.google.com/archive/p/prettytable/wikis/Tutorial.wiki
* https://code.google.com/archive/p/prettytable/wikis/Installation.wiki

Let's move those to this repo as versioned MD or RST files.

There may be some overlap between the tutorial and the README, if so, perhaps they could be merged. Or create a new file for it.

Installation is short and out of date, it says to use `easy_install`, or to manually copy the file to certain directories for different operating systems (with `python2.5` in the examples!). This could be replaced with modern `pip install ...` info near the top of the README.

**Comment by andreykurilin** [comment]
@hugovk cloud.google.com stores these pages in markdown. Here is [Tutorial.wiki](https://www.googleapis.com/storage/v1/b/google-code-archive/o/v2%2Fcode.google.com%2Fprettytable%2Fwiki%2FTutorial.wiki?alt=media).
I tried to quickly compare the sections of ReadMe and Tutorial page: they provide the similar info (ReadMe misses information about `from_html` method).
As for installation - I guess, there is no reason to import `Installation.wiki` page. It can be rewritten with one command that should cover all modern systems `pip install PrettyTable` :)

**Comment by hugovk** [comment]
@andreykurilin Thank you very much for checking! I think we probably remove the link in the README to the wiki then.

Yeah, `pip install PrettyTable` can replace `Installation.wiki`! :)
