### ISSUE TITLE
Add GitHub title + topics

### ISSUE THREAD

**Issue by jhermann** [prettytable/prettytable#32]
Can only be done by a repo or orga owner I guess.

* Set description to “Display tabular data in a visually appealing ASCII table format”
* Add "#readme" to the website self-link, otherwise it's pretty useless.
* Set topics like: python · package · python-3 · utility-library

**Comment by hugovk** [comment]
> * Add "#readme" to the website self-link, otherwise it's pretty useless.

How about putting https://pypi.org/project/PrettyTable/ as the website?

@jezdez Please could you update these?

**Comment by jhermann** [comment]
Re the link: even better. :+1:

**Comment by jezdez** [comment]
Done!
