### ISSUE TITLE
Drop support for EOL Python 2.7 and 3.5

### ISSUE THREAD

**Issue by hugovk** [prettytable/prettytable#36]
Python 2.7 is EOL since 2020-01-01.

Python 3.5 is EOL since 2020-09-30.

After prettytable 1.0 has been released (https://github.com/jazzband/prettytable/issues/18), support for Python 2.7 and 3.5 will be dropped, and released as prettytable 2.0.0.

Prettytable 1.x will be the last to support Python 2.7 and 3.5, and will remain available on PyPI.

The `python_requires` metadata will help those with modern pip (v9+) get the newest version of prettytable that supports their Python version.

**Comment by parth-verma** [comment]
Is this issue up for grabs?

**Comment by hugovk** [comment]
Not yet, still pending the release of prettytable 1.0 (https://github.com/jazzband/prettytable/issues/18), which will be the last to support 2.7.

But thanks for asking!

**Comment by hugovk** [comment]
@parth-verma PrettyTable 1.0 is almost out the door, would you like to take this issue?

We can also drop 3.5 too.

A few things to do: 

* Update Trove classifiers
* Add `Programming Language :: Python :: 3 :: Only` classifier
* Update `python_requires`
* Update `tox.ini`
* Remove from CI
* Update `--target-version` in `.pre-commit-config.yaml`

Also run `pip install -U pyupgrade &&  pyupgrade **/*.py --py36-plus` and add `args: ["--py36-plus"]` to pyupgrade in `.pre-commit-config.yaml`

**Comment by hugovk** [comment]
Up for grabs!

**Comment by hugovk** [comment]
Please see PR https://github.com/jazzband/prettytable/pull/68.
