### ISSUE TITLE
Add ability to specify colgroup attributes for HTML table

### ISSUE THREAD

**Issue by CameronLonsdale** [prettytable/prettytable#39]
The colgroup element has the ability to specify the widths of the individual columns for an HTML table. For inserting a table into confluence for example, it required colgroup to determine the width of columns.

Are you open to including the ability to specify colgroup attributes as an option to get_html_string

Happy to contribute a PR

**Comment by hugovk** [comment]
Please could you give some example before/after output?

**Comment by CameronLonsdale** [comment]
I've achieved it with this as an example:
```python
lines.append(
            "<colgroup>"
            '<col style="width: 200px;"/>'
            '<col style="width: 50px;"/>'
            '<col style="width: 30px;"/>'
            '<col style="width: 30px;"/>'
            '<col style="width: 30px;"/>'
            '<col style="width: 300px;"/>'
            "</colgroup>"
)
```

It just needs to live as its own tag within <table> : https://www.w3schools.com/tags/tag_colgroup.asp.

You could potentially try and compute the widths? or simply just let people specify their own to override

**Comment by hugovk** [comment]
More examples here:

* https://www.w3.org/WAI/tutorials/tables/irregular/

To help visualise, please could you give an example input data, and example output HTML string?
