### ISSUE TITLE
Make escaping data in an HTML table optional

### ISSUE THREAD

**Issue by CameronLonsdale** [prettytable/prettytable#40]
For certain rows, I require the data to be augmented with HTML, and that unfortunately gets escaped here: https://github.com/jazzband/prettytable/blob/master/prettytable.py#L1622

Would you consider adding an option to get_html_string to disable data escaping?

Happy to contribute a PR

**Comment by hugovk** [comment]
Hi, sounds like a good idea, would also solve things like https://github.com/kxxoling/PTable/issues/15 in the fork.

PR welcome!

**Comment by CameronLonsdale** [comment]
Yeah I believe it would. Really, it would be nice to be able to specify a transformation function for the data, with the default being your escape function. I've sub classed and written my own `_get_simple_html_string` so that I can render every row as markdown, rather than it doing the default "escape" behaviour. So being able to specify that transformation function would be epic.

**Comment by loganmarchione** [comment]
+1 for this, would like to be able to use HTML inside a cell (example below)
`<progress class="progress" value="15" max="100">15%</progress>`

**Comment by klauer** [comment]
👍 for this as well. My use case is nested html-rendered prettytables. 

If no one else is looking to jump on this, I might find some time in the nearish future.

**Comment by gilbh** [comment]
Asking if this feature is available already? I am trying to wrap values in one column with `<a href>` tags, but am getting this with `get_html_string()` this:
```
&lt;a href=&#x27;google.com&#x27; ...
```

Perhaps a switch or parameter to `get_html_string()` to disable escaping?

I tried `_get_simple_html_string` but it requires many options (and throws `KeyError` exceptions, e.g. line 1643).

Thanks
Gil

**Comment by hugovk** [comment]
> Asking if this feature is available already? 

Not yet, PRs welcome!



> Perhaps a switch or parameter to `get_html_string()` to disable escaping?

Yes, this is the original suggestion. 

> I tried `_get_simple_html_string` but it requires many options (and throws `KeyError` exceptions, e.g. line 1643).

Yep, in general not a good idea to use functions beginning with an underscore, they're private/internal and liable to change or removal with no warning.

**Comment by gilbh** [comment]
Yup! Thanks!

**Comment by JackSlateur** [comment]
You can always apply a workaround, and monkeypatch the html module:
```python
import html
html.escape = lambda *args, **kwargs: args[0]
from prettytable import PrettyTable
```

**Comment by gilbh** [comment]
Amazing!
