### ISSUE TITLE
ImportError: cannot import name 'MARKDOWN' from 'prettytable'

### ISSUE THREAD

**Issue by vkosuri** [prettytable/prettytable#50]
Hi,

I am getting error cannot import markdown on my Python3.8

``` pycon
>>> from prettytable import MARKDOWN
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'MARKDOWN' from 'prettytable' (/home/vkosuri/github/publish/venv/lib/python3.8/site-packages/prettytable.py)
```

**Comment by hugovk** [comment]
Unfortunately it's not been released yet, and there's not been a release in 7 years. See https://github.com/jazzband/prettytable/issues/18.

In the meantime, you can install directly from GitHub:

```sh
pip install -U git+https://github.com/jazzband/prettytable
```

I'll add this to the README: https://github.com/jazzband/prettytable/pull/51.

**Comment by vkosuri** [comment]
It's worked thank you.
