### ISSUE TITLE
Clarify difference with other forks

### ISSUE THREAD

**Issue by ericpre** [prettytable/prettytable#74]
It seems that there are a couple of forks of prettytable:
- https://github.com/kxxoling/PTable (unmaintained)
- https://github.com/madebr/ptable2 (fork of ptable by @madebr)

From #23, it seems that `ptable` and `prettytable` are not compatible if installed in the same environment. However, do they still have the same API? Are they any features in ptable/ptable2 not available in prettytable?

Now that prettytable is back alive and has a maintenance/distribution infrastructure in place, it would be good to keep the development in this repository and try to merge with the forks (ptable/ptable2)?!

**Comment by hugovk** [comment]
> It seems that there are a couple of forks of prettytable:
> 
> * [kxxoling/PTable](https://github.com/kxxoling/PTable) (unmaintained)
> * [madebr/ptable2](https://github.com/madebr/ptable2) (fork of ptable by @madebr)
> 
> From #23, it seems that `ptable` and `prettytable` are not compatible if installed in the same environment. However, do they still have the same API?

The forks say they the API is compatible. 

https://github.com/kxxoling/PTable says:

> As PTable is a fork of PrettyTable, and compatible with all its APIs, so PTable is usage is the same as PrettyTable, and the installation would cover on the original PrettyTable.

Likewise, https://github.com/madebr/ptable2 says:

> As ptable2 is a fork of PrettyTable, and compatible with all its APIs, so ptable2 is usage is the same as PrettyTable, and the installation would cover on the original PrettyTable.

---

>  Are they any features in ptable/ptable2 not available in prettytable?

Best addressed to the fork authors, or take a look at the commit/PR histories.

---

> Now that prettytable is back alive and has a maintenance/distribution infrastructure in place, it would be good to keep the development in this repository and try to merge with the forks (ptable/ptable2)?!

Sounds like a good idea, PRs welcome! Fork authors (and others!) are welcome to join Jazzband and help with maintenance of this project.

In general, as this library is well used (1.3 million downloads/month!) we should be careful to maintain backwards compatibility, and only break things when necessary, and with a period of deprecation.

**Comment by hugovk** [comment]
Looking at the [merged PRs](https://github.com/kxxoling/PTable/issues?q=is%3Amerged) of PTable, here's a couple of candidates:

* https://github.com/kxxoling/PTable/pull/2 "padding_width = 0 now works" (edit: PR #80)
* https://github.com/kxxoling/PTable/pull/10 "Added `<tbody>` and `<thead>` tags" (edit: PR #81)

**Comment by hugovk** [comment]
> Looking at the [merged PRs](https://github.com/kxxoling/PTable/issues?q=is%3Amerged) of PTable, here's a couple of candidates:
> 
> * [kxxoling/PTable#2](https://github.com/kxxoling/PTable/pull/2) "padding_width = 0 now works" (edit: PR #80)
> * [kxxoling/PTable#10](https://github.com/kxxoling/PTable/pull/10) "Added `<tbody>` and `<thead>` tags" (edit: PR #81)

PRs merged for those!
