### ISSUE TITLE
Cannot use PyInstaller to package application including PrettyTable

### ISSUE THREAD

**Issue by renmu123** [prettytable/prettytable#82]
system: win10 2004
python: 3.8
prettytable: 2.0
pyinstaller: 4.0
pip: 19.2.3

this is my code
```python
# test.py
from prettytable import PrettyTable
x = PrettyTable()
x.field_names = ["City name", "Area", "Population", "Annual Rainfall"]
x.add_row(["Adelaide", 1295, 1158259, 600.5])
x.add_row(["Brisbane", 5905, 1857594, 1146.4])
x.add_row(["Darwin", 112, 120900, 1714.7])
x.add_row(["Hobart", 1357, 205556, 619.5])
x.add_row(["Sydney", 2058, 4336374, 1214.8])
x.add_row(["Melbourne", 1566, 3806092, 646.9])
x.add_row(["Perth", 5386, 1554769, 869.4])

print(x.get_string())

input("input something:")
```
 when I use `pyinstaller -F test.py`，l can not open the .exe file，has the following error

![image](https://user-images.githubusercontent.com/66452398/99203506-c45b9200-27ed-11eb-9723-7524bbda908e.png)

**Comment by hugovk** [comment]
This sounds like https://github.com/jmoiron/humanize/issues/105.

Please can you try a workaround like this?

* https://github.com/jmoiron/humanize/issues/105#issuecomment-594826403

**Comment by renmu123** [comment]
> This sounds like [jmoiron/humanize#105](https://github.com/jmoiron/humanize/issues/105).
> 
> Please can you try a workaround like this?
> 
> * [jmoiron/humanize#105 (comment)](https://github.com/jmoiron/humanize/issues/105#issuecomment-594826403)

it works for me.
l create a file in `.\venv\Lib\site-packages\PyInstaller\hookshook-prettytable.py` 
and add following codes to the file
```python
from PyInstaller.utils.hooks import copy_metadata

datas = copy_metadata('prettytable')
```
