### ISSUE TITLE
[Feature Request] Exporting to Excel

### ISSUE THREAD

**Issue by super233** [prettytable/prettytable#85]
Does the current version support exporting table as excel? If not, feature request!

**Comment by hugovk** [comment]
There's not. The closest is `get_csv_string` which could be imported into Excel:

https://github.com/jazzband/prettytable/blob/1f14f3c2e411e7fec8503def4b025b47e1882d7f/src/prettytable/prettytable.py#L1526-L1535

Tablib can export to Excel, maybe that would meet your requirements?

https://tablib.readthedocs.io

**Comment by super233** [comment]
Ok, thanks :-)
