### ISSUE TITLE
Suggest: auto index column

### ISSUE THREAD

**Issue by yanhuihang** [prettytable/prettytable#90]
It would be good if there is an option to switch on an auto index column. (1, 2, 3 ...)

**Comment by hugovk** [comment]
Please could you give an example of a table with auto index column, and an idea of how the API might look?

**Comment by yanhuihang** [comment]
> Please could you give an example of a table with auto index column, and an idea of how the API might look?

Something like this:

```python
def table(header, dat):
	from prettytable import PrettyTable
	x = PrettyTable()
	x.field_names = [ 'Index' ] + header
	c = 1
	for i in dat:
		x.add_row( [ c ] + i )
		c += 1
	return x
```

```python
>>> import numpy as np
>>> x = table('a b'.split(), np.random.randn(10, 2).tolist())
>>> print(x)
+-------+----------------------+----------------------+
| Index |          a           |          b           |
+-------+----------------------+----------------------+
|   1   |  0.8373683108488006  | -1.9662674211289342  |
|   2   |  0.8166690183400099  | -0.6827019085998253  |
|   3   | -0.34864565952912674 | -0.3828836864526866  |
|   4   |  -0.786195405989435  | -0.28278650269529015 |
|   5   | -0.7737543534146584  | 0.39198996847252016  |
|   6   |  1.2756295710689314  | 0.24976436160178775  |
|   7   |  -2.24766869070198   | -1.0958173510686795  |
|   8   | -0.2123610818363809  | -0.17583602522710734 |
|   9   | -0.9998924564529872  |  -0.78502826234026   |
|   10  |  -0.850991227375058  |  0.3267603399304381  |
+-------+----------------------+----------------------+
```

It looks simple to add this feature - however, I am not able to work on this. Hope this feature can be added later.

**Comment by erictzimas** [comment]
can i work on this?

**Comment by hugovk** [comment]
You can! Please could you say a bit about what sort of API you're thinking of?

The example above shows how it can be implemented by wrapping PrettyTable, with no actual changes to PrettyTable.

So for example, what kind parameters would it have if calling PrettyTable directly without wrapping?

**Comment by erictzimas** [comment]
I was thinking of a solution like this, should I create a PR?  I am sorry for any inconvenience , I am new to contributing.

**Comment by hugovk** [comment]
Thanks, let's continue the discussion in https://github.com/jazzband/prettytable/pull/106 :)

@yanhuihang Your feedback welcome too, is that the sort of thing you had in mind?
