### ISSUE TITLE
Eliminate install-dependency from 'setuptools'

### ISSUE THREAD

**Issue by amdei** [prettytable/prettytable#91]
There is a fragment in setup.py:
https://github.com/jazzband/prettytable/blob/master/setup.py#L29

```
install_requires=["setuptools", "wcwidth"],
```

Does setuptools really necessary here?
Its presence make it difficult to convert prettytable to, for example, deb-package using fpm tool (https://github.com/jordansissel/fpm) - resulted package depends on setuptools too, what, I believe, isn't really necessary.

**Comment by hugovk** [comment]
Yes, it's needed to be able to get the version number using pkg_resources: https://github.com/jazzband/prettytable/pull/66

But this could be replaced with importlib.metadata, in the stdlib from 3.8 and has a backport too:
https://github.com/pypa/setuptools_scm#retrieving-package-version-at-runtime

Would you like to put together a PR? Thanks!

**Comment by hugovk** [comment]
Please see PR https://github.com/jazzband/prettytable/pull/96.
