### ISSUE TITLE
Support markdown table alignment

### ISSUE THREAD

**Issue by endolith** [prettytable/prettytable#97]
If I use `align='r'` it aligns the text to the right in the markup itself:

```
|      |     3 |   101 |   201 |   301 |   401 |   501 |   601 |
|------|-------|-------|-------|-------|-------|-------|-------|
|  WP  | 5.556 | 8.690 | 8.732 | 8.746 | 8.753 | 8.757 | 8.760 |
|  Sim | 5.586 | 8.694 | 8.733 | 8.770 | 8.747 | 8.755 | 8.763 |
| Diff | 0.030 | 0.004 | 0.001 | 0.024 | 0.006 | 0.002 | 0.003 |
```

But this doesn't display aligned in markdown rendering:

|      |     3 |   101 |   201 |   301 |   401 |   501 |   601 |
|------|-------|-------|-------|-------|-------|-------|-------|
|  WP  | 5.556 | 8.690 | 8.732 | 8.746 | 8.753 | 8.757 | 8.760 |
|  Sim | 5.586 | 8.694 | 8.733 | 8.770 | 8.747 | 8.755 | 8.763 |
| Diff | 0.030 | 0.004 | 0.001 | 0.024 | 0.006 | 0.002 | 0.003 |

It should add [markdown's alignment syntax](https://www.pluralsight.com/guides/working-tables-github-markdown#module-theheader-anchor):

```
|      |     3 |   101 |   201 |   301 |   401 |   501 |   601 |
|-----:|------:|------:|------:|------:|------:|------:|------:|
|  WP  | 5.556 | 8.690 | 8.732 | 8.746 | 8.753 | 8.757 | 8.760 |
|  Sim | 5.586 | 8.694 | 8.733 | 8.770 | 8.747 | 8.755 | 8.763 |
| Diff | 0.030 | 0.004 | 0.001 | 0.024 | 0.006 | 0.002 | 0.003 |
```

which renders like this:

|      |     3 |   101 |   201 |   301 |   401 |   501 |   601 |
|-----:|------:|------:|------:|------:|------:|------:|------:|
|  WP  | 5.556 | 8.690 | 8.732 | 8.746 | 8.753 | 8.757 | 8.760 |
|  Sim | 5.586 | 8.694 | 8.733 | 8.770 | 8.747 | 8.755 | 8.763 |
| Diff | 0.030 | 0.004 | 0.001 | 0.024 | 0.006 | 0.002 | 0.003 |

**Comment by hugovk** [comment]
This would be a nice addition, would you like to work on a pull request?

**Comment by hugovk** [comment]
Done in https://github.com/jazzband/prettytable/pull/150
