### ISSUE TITLE
float_format with %

### ISSUE THREAD

**Issue by MicroElf** [prettytable/prettytable#99]
I can't find the way to show float values with % (0.0125 as 1,25% for example)

I tried:
```python
table.float_format = '%0.2f' #(which should be the right way I suppose)
table.float_format = '%0.2'
table.float_format = '0.2%f'
table.float_format = '0.2%'
```

But every time there is an exception raised:
`Exception: Invalid value for float_format! Must be a float format string.`

What am I doing wrong or is it a bug?

**Comment by hugovk** [comment]
https://github.com/jazzband/prettytable#style-options says:

* `float_format` - A string which controls the way floating point data is printed. This works like: `print("%<float_format>f" % data)`


None of the examples would work with plain percent formatting:

```pycon
>>> print("%0.2f" % 0.0125)
0.01
>>> print("%0.2" % 0.0125)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: incomplete format
>>> print("0.2%f" % 0.0125)
0.20.012500
>>> print("0.2%" % 0.0125)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: incomplete format
```

This looks closest? Note the input value is also changed:

```pycon
>>> print("%0.2f%%" % (0.0125*100))
1.25%
````

But note `float_format` provides the leading `%` and trailing `f` already, you can't also supply the `%%` at the very end. Which is to say percentage formatting isn't currently supported.

I suggest you pre-process your data into the required `1,25%` form.

**Comment by rlabbe** [comment]
Use 

    table.float_format = '0.2'

**Comment by MicroElf** [comment]
Thanks you **hugovk**!

`%0.2f%%` is what I was looking for. I thought there should be an elegant way to achieve this output with PrettyTable. Sadly it's apparently not. So, I'll follow your suggestion and format my float numbers where needed into string with % and then add it to PrettyTable.

`float_format` worthless in this case

It would be useful to support percentage formatting for float numbers imho

**Comment by hugovk** [comment]
I'd be open to a PR to add support for that, either `percent_format` or perhaps a general purpose formatter would be more flexible?

**Comment by davzucky** [comment]
@hugovk ,
I looked at the code, and I see you are applying the format like that 

``` python
    def _format_value(self, field, value):
        if isinstance(value, int) and field in self._int_format:
            value = ("%%%sd" % self._int_format[field]) % value
        elif isinstance(value, float) and field in self._float_format:
            value = ("%%%sf" % self._float_format[field]) % value
        return str(value)
```

did you consider using something more like that ```self._float_format[field].format(value)``` where you let the consumer defining exactly what format to apply. For example for percent you could use ```"{:,.2%}``` and thousand and decimal ```{:,.2}```

If you are happy to use ```.format``` I will prepare a PR for you

**Comment by hugovk** [comment]
Thanks for the suggestion, my main concern would be not wanting to break backward compatibility for people using the existing formatting; this is a 12 year old library with nearly 4m downloads per month.

**Comment by davzucky** [comment]
That make sense. I could imagine few other solutions:
1. Add a new property custom_format which for each field a ```callable[[str, Any], str]```. This would allow the consumer of PrettyTable to use any custom format they want. I like this version because you could do something like that
```pycon
>>> "{:,} USD".format(12344556.45)
'12,344,556.45 USD'

```
2. Add a flag with support python2 format, which could be used for few version the time everyone can migrate to the new format.
  
Do you think any of them could work ?

**Comment by hugovk** [comment]
1. Yep, this could work, like a general purpose formatter suggested above (https://github.com/jazzband/prettytable/issues/99#issuecomment-808713023)

2. Python 2 is nearly two years past EOL, we're not adding back support at this stage :)

**Comment by hugovk** [comment]
@MicroElf Please can you have a look at PR https://github.com/jazzband/prettytable/pull/136 and see if it would address your needs?
